export const FETCH_TODO_INIT = 'FETCH_TODO_INIT'
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
export const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE'

export const CREATE_TODO_INIT = 'CREATE_TODO_INIT'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE'

export const TOGGLE_TODO_DONE_INIT = 'TOGGLE_TODO_DONE_INIT'
export const TOGGLE_TODO_DONE_SUCCESS = 'TOGGLE_TODO_DONE_SUCCESS'
export const TOGGLE_TODO_DONE_FAILURE = 'TOGGLE_TODO_DONE_FAILURE'

export const DELETE_TODO_INIT = 'DELETE_TODO_INIT'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

export const CHANGE_DATE_TIME = 'CHANGE_DATE_TIME'
export const CLEAR_DATE_TIME = 'CLEAR_DATE_TIME'
