export const SIGNIN_INTI = 'SIGNIN_INTI'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const GET_USER_DETAILS_INTI = 'GET_USER_DETAILS_INTI'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE'

export const CLEAR_LOGIN_RESP = 'CLEAR_LOGIN_RESP'
